phrases = [
  "3D printers",
  "Academic Presses",
  "Artificial Intelligence",
  "Authority Files",
  "ALIA",
  "Alma",
  "All-Gender Toilets",
  "Arduino Classes",
  "BIBFRAME",
  "Blockchain",
  "Card Catalogues",
  "Censorship",
  "The Cloud",
  "Code Clubs",
  "Code4Lib",
  "Co-design",
  "Community-led librarianship",
  "De-Professionalisation",
  "Design Thinking",
  "the Dewey Decimal System",
  "Digital Dexterity",
  "Digital Humanities",
  "'Digital Natives'",
  "Digital Preservation",
  "Diversity Initiatives",
  "DOAJ",
  "Document Delivery",
  "'Doing more with less'",
  "Drag Queen Storytime",
  "Drone Book Delivery",
  "Elastic Search",
  "Elevator Pitches",
  "Elsevier",
  "FOLIO",
  "GLAM",
  "Gamification",
  "Generous Interfaces",
  "Genrefication",
  "Getting Rid of the OPAC",
  "The Glass Escalator",
  "IFLA",
  "Information Literacy",
  "Information Overload",
  "Innovation",
  "Institutional Repositories",
  "Inter-Library Loans",
  "the Internet of Things",
  "Intersectional Librarianship",
  "Journal Flipping",
  "Koha ILS",
  "Legal Deposit",
  "Lego Clubs",
  "LIANZA",
  "Libguides",
  "Librarian Stereotypes",
  "Linked Open Data",
  "Little Free Libraries",
  "MaRC",
  "Makerspaces",
  "Marginalia",
  "Middle Class White Guys Who 'Never Use the Library'",
  "Nap Pods",
  "National Bibliographic Databases",
  "Nazis in the Meeting Room",
  "OCLC",
  "OERs",
  "Old Book Smell",
  "One-Shot Instruction",
  "Open Access",
  "Open Source",
  "Plan S",
  'PLOSOne',
  "Passive-Aggressive Signage",
  "Passwords on Post-It Notes",
  "Patron Privacy",
  "Patron-Driven Acquisitions",
  "Professional Certification",
  "Radical Librarians",
  "Research Offices",
  "SciHub",
  "Semantic Markup",
  "Stain-Resistant Furniture",
  "Student Success Metrics",
  "Summon",
  "Tenure",
  "'Thinking Like a Startup'",
  "Vendor Consolidation",
  "Wikipedia"
]

module.exports = phrases