const actions =
[
  'Lending',
  'Cataloguing',
  'Standardising',
  'Co-ordinating',
  'Embracing',
  'Revolutionising',
  'Saving',
  'Restoring',
  'Preserving',
  'Reading',
  'Weeding',
  'Shelving',
  'Helping'
]

const adverbs =
[
  'How',
  'When',
  'Where',
  'Why'
]

const changeWords =
[
  'Improve',
  'Revolutionise',
  'Rationalise',
  'Re-Imagine',
  'Rethink',
  'Embrace',
  'Catalogue',
  'Standardise'
]

const cliches = [
  "3D Printers",
  "Academic Presses",
  "Artificial Intelligence",
  "Authority Files",
  "ALA",
  "ALIA",
  "Alma",
  "All-Gender Toilets",
  "Arduinos",
  "Austlang Codes",
  "BIBFRAME",
  "Blockchain",
  "Card Catalogues",
  "Cardigans",
  "Censorship",
  "CILIP",
  "Citation Guides",
  "The Cloud",
  "Code Clubs",
  "Code4Lib",
  "Co-Design",
  "Community-Led Librarianship",
  "Controlled Vocabularies",
  "CRAAP",
  "Data Repositories",
  "De-Professionalisation",
  "Design Thinking",
  "the Dewey Decimal System",
  "Digital Dexterity",
  "Digital Humanities",
  "'Digital Natives'",
  "Digital Preservation",
  "Diversity Initiatives",
  "DOAJ",
  "Document Delivery",
  "'Doing More With Less'",
  "Drag Queen Storytime",
  "Drone Book Delivery",
  "Dublin Core",
  "Elastic Search",
  "Elevator Pitches",
  "Elsevier",
  "FOLIO",
  "GLAM",
  "Gamification",
  "Generous Interfaces",
  "Genrefication",
  "Getting Rid Of The OPAC",
  "Green Open Access",
  "The Glass Escalator",
  "h-indexes",
  "IFLA",
  "Information Literacy",
  "Information Overload",
  "Innovation",
  "Institutional Repositories",
  "Inter-Library Loans",
  "the Internet of Things",
  "Intersectional Librarianship",
  "Journal Flipping",
  "Koha ILS",
  "LCSH",
  "Legal Deposit",
  "Lego Clubs",
  "LIANZA",
  "Libguides",
  "Librarian Stereotypes",
  "Linked Open Data",
  "Little Free Libraries",
  "MaRC",
  "Makerspaces",
  "Marginalia",
  "Metadata",
  "Minecraft",
  "Nap Pods",
  "National Bibliographic Databases",
  "Nazis In The Meeting Room",
  "newCardigan",
  "OCLC",
  "OERs",
  "Old Book Smell",
  "One-Shot Instruction",
  "Open Access",
  "Open Source",
  "Plan S",
  'PLOSOne',
  "Passive-Aggressive Signage",
  "Patron Privacy",
  "Patron-Driven Acquisitions",
  "P-hacking",
  "Professional Certification",
  "Radical Librarians",
  "Research Network Graphs",
  "SciHub",
  "Semantic Markup",
  "Stain-Resistant Furniture",
  "Student Success Metrics",
  "Summon",
  "Tenure",
  "'Thinking Like A Startup'",
  "Union Catalogues",
  "Vendor Consolidation",
  "Vocational Awe",
  "Wikidata",
  "Wikipedia"
]

const users =
[
  'Seniors',
  'Academics',
  'Funders',
  'Donors',
  'Councillors',
  'Dog People',
  'Cat Lovers',
  'Authors',
  'Readers',
  'Enbies',
  'Parents',
  'Mothers',
  'Fathers',
  'Families',
  'Millennials',
  'Generation Z',
  'Students',
  'Teens',
  'Screenagers',
  'Toddlers',
  'Babies'
]

module.exports = {
  actions: actions,
  adverbs: adverbs,
  cliches: cliches,
  changeWords: changeWords,
  users: users
}